import { Navbar } from '@/components'

export const metadata = {
    title: 'Node.js Nedir?',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <>
            {children}
        </>
    )
}
